name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      working-directory: ./polls_app/
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
    - name: Run Tests
      working-directory: ./polls_app
      run: |
        pip install pytest pytest-cov
        pytest polls/tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html